-- MySQL Script generated by MySQL Workbench
-- Thu May  3 21:36:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sqldi
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ksqdigital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ksqdigital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ksqdigital` DEFAULT CHARACTER SET utf8 ;
USE `ksqdigital` ;

-- -----------------------------------------------------
-- Table `ksqdigital`.`insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksqdigital`.`insumos` (
  `InsCodigo` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'ID de cada insumo',
  `InsNombre` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'Nombre de los insumos',
  `InsUnidadMedida` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'Unidad de medida en la que se realizan los calculos de los insumos\n',
  `InsPrecio` INT(11) NULL DEFAULT NULL COMMENT 'Precio unitario de cada insumo\n',
  PRIMARY KEY (`InsCodigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ksqdigital`.`ordenproduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksqdigital`.`ordenproduccion` (
  `OrdPId` INT(11) NOT NULL COMMENT 'Id de las ordenes de producción',
  `OrdPFecha` DATE NULL DEFAULT NULL COMMENT 'Fecha en la que se registra la orden de producción',
  `OrdPAsignada` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'Persona a la que se le asigna la orden de producción\n',
  `OrdPFuente` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'Persona que asigno la orden de producción\n',
  `OrdPCant` INT(11) NULL DEFAULT NULL COMMENT 'Cantidad solicitada por cada producto',
  `OrdPObservaciones` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'Observaciones registradas en cada orden de producción \n',
  PRIMARY KEY (`OrdPId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ksqdigital`.`porins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksqdigital`.`porins` (
  `idPorIns` INT(11) NOT NULL,
  PRIMARY KEY (`idPorIns`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ksqdigital`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksqdigital`.`productos` (
  `ProCodigo` INT(11) NOT NULL COMMENT 'ID  de producto\n',
  `ProNombre` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'Nombre del producto',
  `ProPresentacion` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'Presentación en la que se vende cada producto una vez este fabricado',
  `ProDescripcion` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'Descripción del producto',
  `ProPrecioBogota` INT(11) NULL DEFAULT NULL COMMENT 'Precio del producto en Bogotá',
  `ProPrecioNacional` INT(11) NULL DEFAULT NULL COMMENT 'Precio del producto a nivel nacional',
  `ProMaquila` INT(11) NULL DEFAULT NULL COMMENT 'Costo de producción del producto',
  PRIMARY KEY (`ProCodigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ksqdigital`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ksqdigital`.`proveedor` (
  `ProvCodigo` INT(11) NOT NULL COMMENT 'Id de proveedor\n',
  `ProvNombre` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT 'Nombre del proveedor\n',
  PRIMARY KEY (`ProvCodigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
